### ISSUE TITLE
I clone to my machine but it doesnt work

### ISSUE THREAD

**Issue by BrownAJKE** [suresh-ramani/lara9sanctum-auth-vite-vue3#1]
Hi,
Cloned this project to my machine and it doesnt work, when I open it on browser it shows a blank page.

**Comment by suresh-ramani** [comment]
Can you share a screenshot of the browser console? or can you share the error?

**Comment by BrownAJKE** [comment]
No errors on console, absolutely nothing

**Comment by suresh-ramani** [comment]
Can we connect through anydesk?

**Comment by BrownAJKE** [comment]
Yes sure

**Comment by suresh-ramani** [comment]
Share anydesk number through ramani.suresh41@gmail.com

**Comment by BrownAJKE** [comment]
Check your email

**Comment by suresh-ramani** [comment]
Not received.

**Comment by suresh-ramani** [comment]
share here

**Comment by suresh-ramani** [comment]
accept

**Comment by suresh-ramani** [comment]
I think there is some permission issue in your machine.

**Comment by BrownAJKE** [comment]
can we do a zoom?

**Comment by suresh-ramani** [comment]
Please upload your code and share the repository link.

I will check it.

**Comment by suresh-ramani** [comment]
Upload code i will review it.
